"""Research sidecar primitives, exposed without eager optional dependencies."""

from importlib import import_module


_EXPORT_MODULES = {
    "ReplayContractError": "quantpits.research.replay",
    "ReplayInputError": "quantpits.research.replay",
    "ResearchRankingReplay": "quantpits.research.replay",
    "revalidate_replay_result": "quantpits.research.replay",
    "load_sealed_replay_inputs": "quantpits.research.replay",
    "write_replay_output": "quantpits.research.replay",
    "ExecutionAssumption": "quantpits.research.accounting",
    "ShadowAccountingContractError": "quantpits.research.accounting",
    "ShadowIntentBatch": "quantpits.research.accounting",
    "ShadowPortfolioState": "quantpits.research.accounting",
    "ShadowPortfolioTransition": "quantpits.research.accounting",
    "ShadowQuoteSnapshot": "quantpits.research.accounting",
    "ShadowTransitionResult": "quantpits.research.accounting",
    "AnchorPriceSnapshot": "quantpits.research.intents",
    "CurrentRuleIntentDefinition": "quantpits.research.intents",
    "CurrentRuleShadowIntentPlanner": "quantpits.research.intents",
    "IntentPlanningContractError": "quantpits.research.intents",
    "IntentPlanningParityError": "quantpits.research.intents",
    "IntentPlanningResult": "quantpits.research.intents",
    "ARM_IDS": "quantpits.research.historical_cycle",
    "CashPriceReceipt": "quantpits.research.historical_cycle",
    "HistoricalCycleContractError": "quantpits.research.historical_cycle",
    "HistoricalCycleInputError": "quantpits.research.historical_cycle",
    "HistoricalCycleResult": "quantpits.research.historical_cycle",
    "HistoricalShadowCycleReplay": "quantpits.research.historical_cycle",
    "PublicationReceipt": "quantpits.research.historical_cycle",
    "QlibCashPriceObserver": "quantpits.research.historical_cycle",
    "ReplayProfileReceipt": "quantpits.research.historical_cycle",
    "load_replay_profile": "quantpits.research.historical_cycle",
    "rounding_adjustment_within_bound": "quantpits.research.historical_cycle",
    "write_historical_cycle_output": "quantpits.research.historical_cycle",
    "HistoricalShadowWindowReplay": "quantpits.research.historical_window",
    "HistoricalWindowContractError": "quantpits.research.historical_window",
    "HistoricalWindowInputError": "quantpits.research.historical_window",
    "HistoricalWindowResult": "quantpits.research.historical_window",
    "SequentialPriorStateSet": "quantpits.research.historical_window",
    "compact_window_summary": "quantpits.research.historical_window",
    "revalidate_historical_window_result": "quantpits.research.historical_window",
    "HistoricalWindowPublicationContractError": "quantpits.research.historical_window_publication",
    "HistoricalWindowPublicationInputError": "quantpits.research.historical_window_publication",
    "WindowPublicationReceipt": "quantpits.research.historical_window_publication",
    "build_historical_window_artifacts": "quantpits.research.historical_window_publication",
    "write_historical_window_output": "quantpits.research.historical_window_publication",
    "CreateOnlyDefinitionBundleStore": "quantpits.research.definition_store",
    "DefinitionBundleMember": "quantpits.research.definition_store",
    "DefinitionBundleRequest": "quantpits.research.definition_store",
    "DefinitionStoreContractError": "quantpits.research.definition_store",
    "DefinitionStoreInputError": "quantpits.research.definition_store",
    "DefinitionStoreReceipt": "quantpits.research.definition_store",
    "revalidate_definition_bundle_request": "quantpits.research.definition_store",
    "CompiledShadowForwardDefinitions": "quantpits.research.forward_definitions",
    "DigestReference": "quantpits.research.forward_definitions",
    "ForwardDefinitionContractError": "quantpits.research.forward_definitions",
    "ShadowExecutionAssumption": "quantpits.research.forward_definitions",
    "ShadowForwardProtocol": "quantpits.research.forward_definitions",
    "ShadowStrategyDefinition": "quantpits.research.forward_definitions",
    "SourceMember": "quantpits.research.forward_definitions",
    "compile_shadow_forward_definitions": "quantpits.research.forward_definitions",
    "ForwardObservationContractError": "quantpits.research.forward_observation",
    "ForwardObservationInputError": "quantpits.research.forward_observation",
    "ObservedForwardDefinitionCandidate": "quantpits.research.forward_observation",
    "FreshChampionSegmentCandidate": "quantpits.research.forward_observation",
    "observe_shadow_forward_definition_candidate": "quantpits.research.forward_observation",
    "observe_frozen_shadow_forward_definition_candidate": "quantpits.research.forward_observation",
    "observe_fresh_champion_segment_candidate": "quantpits.research.forward_observation",
    "AUTHORIZATION_ACTION": "quantpits.research.forward_definition_publication",
    "FRESH_AUTHORIZATION_ACTION": "quantpits.research.forward_definition_publication",
    "FrozenDefinitionPublicationContractError": "quantpits.research.forward_definition_publication",
    "FrozenDefinitionPublicationInputError": "quantpits.research.forward_definition_publication",
    "FrozenDefinitionPublicationPlan": "quantpits.research.forward_definition_publication",
    "FrozenDefinitionBytePublicationResult": "quantpits.research.forward_definition_publication",
    "prepare_frozen_shadow_forward_definition_publication": "quantpits.research.forward_definition_publication",
    "publish_frozen_shadow_forward_definition_bundle": "quantpits.research.forward_definition_publication",
    "prepare_fresh_champion_segment_definition_publication": "quantpits.research.forward_definition_publication",
    "publish_fresh_champion_segment_definition_bundle": "quantpits.research.forward_definition_publication",
    "FORWARD_EVIDENCE_AUTHORIZATION_ACTION": "quantpits.research.forward_definition_evidence",
    "ForwardDefinitionEvidenceContractError": "quantpits.research.forward_definition_evidence",
    "ForwardDefinitionEvidenceInputError": "quantpits.research.forward_definition_evidence",
    "ForwardDefinitionEvidenceStoreReceipt": "quantpits.research.forward_definition_evidence",
    "ForwardDefinitionEvidencePlan": "quantpits.research.forward_definition_evidence",
    "ForwardDefinitionEvidenceResult": "quantpits.research.forward_definition_evidence",
    "prepare_forward_definition_evidence": "quantpits.research.forward_definition_evidence",
    "publish_forward_definition_evidence": "quantpits.research.forward_definition_evidence",
    "adopt_forward_definition_evidence": "quantpits.research.forward_definition_evidence",
    "ForwardPortfolioSourceContractError": "quantpits.research.forward_portfolio_source",
    "ForwardPortfolioSourceInputError": "quantpits.research.forward_portfolio_source",
    "ForwardPortfolioSourceObservation": "quantpits.research.forward_portfolio_source",
    "observe_forward_portfolio_source": "quantpits.research.forward_portfolio_source",
    "ForwardBootstrapContractError": "quantpits.research.forward_bootstrap",
    "ForwardBootstrapInputError": "quantpits.research.forward_bootstrap",
    "MatchedForwardBootstrapStoreReceipt": "quantpits.research.forward_bootstrap",
    "MatchedForwardBootstrapPlan": "quantpits.research.forward_bootstrap",
    "MatchedForwardBootstrapResult": "quantpits.research.forward_bootstrap",
    "prepare_matched_forward_bootstrap": "quantpits.research.forward_bootstrap",
    "publish_matched_forward_bootstrap": "quantpits.research.forward_bootstrap",
}


def __getattr__(name):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError("module %r has no attribute %r" % (__name__, name))
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value

__all__ = [
    "ReplayContractError",
    "ReplayInputError",
    "ResearchRankingReplay",
    "revalidate_replay_result",
    "load_sealed_replay_inputs",
    "write_replay_output",
    "ExecutionAssumption",
    "ShadowAccountingContractError",
    "ShadowIntentBatch",
    "ShadowPortfolioState",
    "ShadowPortfolioTransition",
    "ShadowQuoteSnapshot",
    "ShadowTransitionResult",
    "AnchorPriceSnapshot",
    "CurrentRuleIntentDefinition",
    "CurrentRuleShadowIntentPlanner",
    "IntentPlanningContractError",
    "IntentPlanningParityError",
    "IntentPlanningResult",
    "ARM_IDS",
    "CashPriceReceipt",
    "HistoricalCycleContractError",
    "HistoricalCycleInputError",
    "HistoricalCycleResult",
    "HistoricalShadowCycleReplay",
    "PublicationReceipt",
    "QlibCashPriceObserver",
    "ReplayProfileReceipt",
    "load_replay_profile",
    "rounding_adjustment_within_bound",
    "write_historical_cycle_output",
    "HistoricalShadowWindowReplay",
    "HistoricalWindowContractError",
    "HistoricalWindowInputError",
    "HistoricalWindowResult",
    "SequentialPriorStateSet",
    "compact_window_summary",
    "revalidate_historical_window_result",
    "HistoricalWindowPublicationContractError",
    "HistoricalWindowPublicationInputError",
    "WindowPublicationReceipt",
    "build_historical_window_artifacts",
    "write_historical_window_output",
    "CreateOnlyDefinitionBundleStore",
    "DefinitionBundleMember",
    "DefinitionBundleRequest",
    "DefinitionStoreContractError",
    "DefinitionStoreInputError",
    "DefinitionStoreReceipt",
    "revalidate_definition_bundle_request",
    "CompiledShadowForwardDefinitions",
    "DigestReference",
    "ForwardDefinitionContractError",
    "ShadowExecutionAssumption",
    "ShadowForwardProtocol",
    "ShadowStrategyDefinition",
    "SourceMember",
    "compile_shadow_forward_definitions",
    "ForwardObservationContractError",
    "ForwardObservationInputError",
    "ObservedForwardDefinitionCandidate",
    "FreshChampionSegmentCandidate",
    "observe_shadow_forward_definition_candidate",
    "observe_frozen_shadow_forward_definition_candidate",
    "observe_fresh_champion_segment_candidate",
    "AUTHORIZATION_ACTION",
    "FRESH_AUTHORIZATION_ACTION",
    "FrozenDefinitionPublicationContractError",
    "FrozenDefinitionPublicationInputError",
    "FrozenDefinitionPublicationPlan",
    "FrozenDefinitionBytePublicationResult",
    "prepare_frozen_shadow_forward_definition_publication",
    "publish_frozen_shadow_forward_definition_bundle",
    "prepare_fresh_champion_segment_definition_publication",
    "publish_fresh_champion_segment_definition_bundle",
    "FORWARD_EVIDENCE_AUTHORIZATION_ACTION",
    "ForwardDefinitionEvidenceContractError",
    "ForwardDefinitionEvidenceInputError",
    "ForwardDefinitionEvidenceStoreReceipt",
    "ForwardDefinitionEvidencePlan",
    "ForwardDefinitionEvidenceResult",
    "prepare_forward_definition_evidence",
    "publish_forward_definition_evidence",
    "adopt_forward_definition_evidence",
    "ForwardPortfolioSourceContractError",
    "ForwardPortfolioSourceInputError",
    "ForwardPortfolioSourceObservation",
    "observe_forward_portfolio_source",
    "ForwardBootstrapContractError",
    "ForwardBootstrapInputError",
    "MatchedForwardBootstrapStoreReceipt",
    "MatchedForwardBootstrapPlan",
    "MatchedForwardBootstrapResult",
    "prepare_matched_forward_bootstrap",
    "publish_matched_forward_bootstrap",
]
