name: Bug Report
description: Create a report to help us improve QuantPits
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g. 3.8.10
    validations:
      required: true
  - type: textarea
    id: system_info
    attributes:
      label: System & Workspace Configuration
      description: Please provide details about your OS and workspace configuration (e.g., how run_env.sh variables are set).
      placeholder: e.g. Ubuntu 22.04, QUANT_WORKSPACE=workspaces/CSI300_Base
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Logs or Screenshots
      description: Please paste the complete traceback logs or attach a screenshot here.
      render: shell
    validations:
      required: true
