"""Ensemble runtime service primitives."""

from quantpits.ensemble.analytics import (
    CorrelationAnalysisRequest,
    CorrelationAnalysisResult,
    ModelContributionSaveResult,
    build_model_contribution_payload,
    calculate_loo_contribution,
    compute_prediction_correlation,
    run_correlation_analysis,
    save_model_contribution_snapshot,
    summarize_correlation_matrix,
)
from quantpits.ensemble.backtest import (
    BacktestExecutionRequest,
    BacktestExecutionResult,
    BacktestPerformanceSummary,
    build_backtest_performance_summary,
    execution_window_from_signal,
    print_backtest_performance_summary,
    run_backtest,
    run_backtest_execution,
    run_detailed_backtest_analysis,
)
from quantpits.ensemble.charts import (
    ChartGenerationRequest,
    ChartGenerationResult,
    build_chart_outputs,
    ensemble_nav_chart_path,
    ensemble_weights_chart_path,
    generate_charts,
)
from quantpits.ensemble.comparison import (
    ComboComparisonRequest,
    ComboComparisonResult,
    build_combo_comparison_frame,
    compare_combos,
    run_combo_comparison,
)
from quantpits.ensemble.config import load_ensemble_run_config
from quantpits.ensemble.execution import (
    EnsembleExecutionContext,
    LoadedPredictionBundle,
    combo_manifest_records,
    required_models_from_combos,
    success_manifest_records,
    valid_models_for_combo,
)
from quantpits.ensemble.ledger import (
    FusionLedgerEntry,
    append_fusion_ledger,
    build_fusion_ledger_record,
)
from quantpits.ensemble.persistence import (
    PredictionSaveRequest,
    PredictionSaveResult,
    save_ensemble_predictions,
)
from quantpits.ensemble.pipeline import (
    SingleComboPipelineHooks,
    SingleComboPipelineRequest,
    SingleComboPipelineResult,
    default_single_combo_pipeline_hooks,
    run_single_combo,
    run_single_combo_pipeline,
)
from quantpits.ensemble.risk_report import (
    RiskLeaderboardRequest,
    RiskLeaderboardResult,
    build_risk_leaderboard,
    calculate_safe_risk,
    leaderboard_output_path,
    risk_analysis_and_leaderboard,
)
from quantpits.ensemble.service import (
    EnsembleFusionService,
    prepare_ensemble_run,
    prepared_plan_json,
    render_prepared_plan,
)
from quantpits.ensemble.types import (
    EnsembleExecutionHooks,
    EnsembleRunConfig,
    EnsembleRunOptions,
    EnsembleRunSummary,
    PreparedEnsembleRun,
    options_from_namespace,
    options_to_namespace,
)

__all__ = [
    "BacktestExecutionRequest",
    "BacktestExecutionResult",
    "BacktestPerformanceSummary",
    "CorrelationAnalysisRequest",
    "CorrelationAnalysisResult",
    "ComboComparisonRequest",
    "ComboComparisonResult",
    "ChartGenerationRequest",
    "ChartGenerationResult",
    "EnsembleExecutionHooks",
    "EnsembleExecutionContext",
    "EnsembleFusionService",
    "EnsembleRunConfig",
    "EnsembleRunOptions",
    "EnsembleRunSummary",
    "FusionLedgerEntry",
    "LoadedPredictionBundle",
    "ModelContributionSaveResult",
    "PredictionSaveRequest",
    "PredictionSaveResult",
    "PreparedEnsembleRun",
    "RiskLeaderboardRequest",
    "RiskLeaderboardResult",
    "SingleComboPipelineHooks",
    "SingleComboPipelineRequest",
    "SingleComboPipelineResult",
    "append_fusion_ledger",
    "build_backtest_performance_summary",
    "build_model_contribution_payload",
    "build_chart_outputs",
    "build_combo_comparison_frame",
    "build_fusion_ledger_record",
    "build_risk_leaderboard",
    "calculate_loo_contribution",
    "calculate_safe_risk",
    "combo_manifest_records",
    "compare_combos",
    "compute_prediction_correlation",
    "default_single_combo_pipeline_hooks",
    "ensemble_nav_chart_path",
    "ensemble_weights_chart_path",
    "execution_window_from_signal",
    "generate_charts",
    "leaderboard_output_path",
    "load_ensemble_run_config",
    "options_from_namespace",
    "options_to_namespace",
    "prepare_ensemble_run",
    "prepared_plan_json",
    "print_backtest_performance_summary",
    "required_models_from_combos",
    "render_prepared_plan",
    "risk_analysis_and_leaderboard",
    "run_backtest",
    "run_backtest_execution",
    "run_combo_comparison",
    "run_correlation_analysis",
    "run_detailed_backtest_analysis",
    "run_single_combo",
    "run_single_combo_pipeline",
    "save_ensemble_predictions",
    "save_model_contribution_snapshot",
    "summarize_correlation_matrix",
    "success_manifest_records",
    "valid_models_for_combo",
]
